server:
    port: 8084

spring:
  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/board?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia
    username: root
    password: root
    pool:
      max-size: 100
      validation-query: SELECT 1


#logging:
#  level:
#    org:
#      springframework:
#        r2dbc:DEBUG